application: peg-solitarie-backend-udacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: api.api

- url: /.*
  script: hello.app

libraries:
- name: endpoints
  version: latest
